Conference website pull request
codecaiine/conference-website pull request #2
Opened 2021-08-12 17:51 UTC by codecaiine

- I created a new repository for the capstone project
- I created a new branch for mobile and desktop
- I set up linters for HTML CSS & Javascript
- I added Javascript Scripts to create speakers section Dynamically
- I added descriptive readme file
- I fixed linters errors

2021-08-12 20:10 UTC, abruzy requested changes
Hi @codecaiine 👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_1. Kindly add the link to the video record presenting the features of your application, you can either use loom or zoom._
_2. Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 20:10 UTC, abruzy commented on README.md
> +## Acknowledgments
kindly give credit to [Cindy Shin](https://www.behance.net/adagio07) the [original author of the design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) as required by the [Creative Common Licence](https://creativecommons.org/licenses/)

2021-08-12 20:10 UTC, abruzy commented on index.html
> +            <div class="row mb-2" id="speakers-list"></div>
your featured speaker's sections should have two columns of three articles each

<img width="1033" alt="Screenshot 2021-08-12 at 20 36 29" src="https://user-images.githubusercontent.com/34798898/129258142-46ac03a1-c70e-47f9-ad54-4c54969f6de9.png">

Here's yours, you have 4

<img width="1207" alt="Screenshot 2021-08-12 at 20 37 19" src="https://user-images.githubusercontent.com/34798898/129258222-db0b1373-762a-44e9-86aa-b511c80448fc.png">

So please fix this

2021-08-12 20:10 UTC, abruzy commented on index.html
> +    </section>
follow semantic HTML, `footer` should have the `footer` tag

2021-08-12 20:10 UTC, abruzy commented on index.html
> +        </div>
use Semantic HTML, this is still a `nav` tag, the only difference is we have two navbars one is the top nav and the other is bottom nav, so change the div to `nav` tag

Making use of semantic HTML is very good as this helps in improving your application SEO

2021-08-12 22:23 UTC, codecaiine commented on index.html
> +            <div class="row mb-2" id="speakers-list"></div>
I fixed it.

![update](https://user-images.githubusercontent.com/6615394/129277515-0d43ffe4-e4ac-4d55-ba2b-a5c07293f663.PNG)

2021-08-12 22:35 UTC, codecaiine commented on index.html
> +    </section>
![footer](https://user-images.githubusercontent.com/6615394/129278502-7cf153b0-6906-41d7-904b-80272a0e05d9.PNG)

2021-08-12 22:35 UTC, codecaiine commented on index.html
> +        </div>
![nav](https://user-images.githubusercontent.com/6615394/129278534-bc799e16-e363-4041-8813-f8ce4750c090.PNG)

2021-08-12 22:36 UTC, codecaiine commented on README.md
> +## Acknowledgments
![Ak](https://user-images.githubusercontent.com/6615394/129278635-cfe78148-a70c-43e7-812b-ae83c3cdf0b6.PNG)

2021-08-13 02:46 UTC, rloterh commented on README.md
> +## Acknowledgments
This issue is well resolved! ✔️

2021-08-13 02:47 UTC, rloterh commented on index.html
> +            <div class="row mb-2" id="speakers-list"></div>
This issue is well resolved! ✔️

2021-08-13 02:48 UTC, rloterh commented on index.html
> +    </section>
This issue is well resolved! ✔️

2021-08-13 03:17 UTC, rloterh requested changes
Hi Yannick-Noel, 

You did exceptionally great on this project, and for making the changes requested by the previous reviewer!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚆 🚥 

## Good Points 👍  
- Great UI design
- Responsive
- No linter errors

## Required Changes ♻️
- [ ] _Kindy check the comments under this reviews_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider the comments marked [OPTIONAL] under this review:


Cheers..Happy coding..and keep Soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 3 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 03:17 UTC, rloterh commented on index.html
> +            <div class="row mb-2" id="speakers-list"></div>
- [ ] OPTIONAL
Also, kindly notice that the images of speakers in the `Featured Speakers` section has a decorated `background images`. Kindly endeavor to improve upon this aspect

**Your design (Featured Speakers section):**
![image](https://user-images.githubusercontent.com/12745474/129298656-30ef2a74-d054-489e-b477-5a1b7d1573b9.png)


**The original design (Featured Speakers section):**
![image](https://user-images.githubusercontent.com/12745474/129298749-e13f31c2-5db0-4274-bc06-d011bcf3d555.png)

2021-08-13 03:17 UTC, rloterh commented on about.html
> +
- [ ] OPTIONAL
To enhance a cleaner code kindly endeavor to remove **all** extra lines which are serving no purpose in your code.

2021-08-13 03:17 UTC, rloterh commented on README.md
> +[Demo video link](https://www.loom.com/share/0031406c6c2b4a87b2066580a29365fb)
- [ ] Nice job by adding video description of your project as requested by the previous code reviewer. However, your video description **not detailed**. Kindly ensure that video description also covers some salient aspect your **code base** for this project. (Video should be at least 4mins and max of 5 mins)

2021-08-13 12:06 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 12:11 UTC, merged